# -*- coding: utf-8 -*-
"""Functions_2i_Montico_Caldana.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-X8KjGjhCc3aQRBbeOeAuZNXusXX67gh
"""

import numpy as np
from cvxopt import matrix, solvers

def rbf_kernel(X1, X2, gamma):
    """
    Compute the RBF (Gaussian) kernel matrix.
    """
    # Compute squared Euclidean distances efficiently using broadcasting.
    X1_sq = np.sum(X1**2, axis=1).reshape(-1, 1)
    X2_sq = np.sum(X2**2, axis=1).reshape(1, -1)
    dist_sq = X1_sq + X2_sq - 2 * np.dot(X1, X2.T)

    # Ensure non-negativity due to potential floating point inaccuracies.
    dist_sq = np.maximum(dist_sq, 0)
    return np.exp(-gamma * dist_sq)

def solve_svm_dual_cvxopt(X, y, C, gamma):
    """
    Solve the SVM dual problem using CVXOPT.
    """
    n_samples = X.shape[0]
    # Cast labels to float type for numerical stability.
    y = y.astype(float)

    # Precompute the Radial Basis Function (RBF) kernel matrix.
    K = rbf_kernel(X, X, gamma)

    # Setup matrices for CVXOPT quadratic programming (QP) solver.
    # The objective function is 0.5 * alpha^T * P * alpha + q^T * alpha.
    # P corresponds to the term diag(y) * K * diag(y).
    P = matrix(np.outer(y, y) * K)
    q = matrix(-np.ones(n_samples))

    # Inequality constraints: G * alpha <= h. Here, 0 <= alpha_i <= C.
    # This implies: -alpha_i <= 0 and alpha_i <= C.
    G_std = -np.eye(n_samples) # For -alpha_i <= 0
    G_slack = np.eye(n_samples)  # For alpha_i <= C
    G = matrix(np.vstack((G_std, G_slack)))

    h_std = np.zeros(n_samples) # For -alpha_i <= 0
    h_slack = np.ones(n_samples) * C # For alpha_i <= C
    h = matrix(np.hstack((h_std, h_slack)))

    # Equality constraint: A * alpha = b. Here, sum(alpha_i * y_i) = 0.
    A = matrix(y.reshape(1, -1))
    b = matrix(np.zeros(1))

    # Solve the QP problem using CVXOPT. Disable progress output for cleaner logs.
    solvers.options['show_progress'] = False
    sol = solvers.qp(P, q, G, h, A, b)

    # Extract the optimized alpha values.
    alpha = np.array(sol['x']).flatten()

    # Identify support vectors: 0 < alpha_i < C (margin support vectors).
    # A small tolerance (tol) is used to account for floating-point precision issues.
    tol = 1e-5
    sv_indices = np.where((alpha > tol) & (alpha < C - tol))[0]

    # Calculate the bias 'b' using margin support vectors.
    if len(sv_indices) > 0:
        # Standard formula for bias: b = y_k - sum(alpha_j * y_j * K_jk).
        # Averaging over multiple margin support vectors for robustness.
        b = np.mean(y[sv_indices] - (alpha * y) @ K[:, sv_indices])
    else:
        # Fallback if no margin support vectors are found. Use all active support vectors.
        sv_all = np.where(alpha > tol)[0]
        if len(sv_all) > 0:
             b = np.mean(y[sv_all] - (alpha * y) @ K[:, sv_all])
        else:
             # If no support vectors are found at all, set bias to 0.
             b = 0.0

    return alpha, b, sol

def svm_predict(X_train, y_train, alpha, b, X_test, gamma):
    """
    Predict labels for the test set using the trained SVM parameters.
    """
    # Only consider support vectors for prediction to reduce computational cost.
    tol = 1e-5
    sv_idx = alpha > tol

    # Handle edge case where no support vectors are identified.
    if not np.any(sv_idx):
        return np.ones(X_test.shape[0]) # Default to class +1 as an arbitrary fallback.

    alpha_sv = alpha[sv_idx]
    y_sv = y_train[sv_idx]
    X_sv = X_train[sv_idx]

    # Compute the kernel matrix between test data and support vectors.
    K_test = rbf_kernel(X_test, X_sv, gamma)

    # Calculate the decision function: sign(sum(alpha_sv * y_sv * K_test) + b).
    decision = K_test @ (alpha_sv * y_sv) + b

    # Assign class labels based on the sign of the decision function.
    y_pred = np.sign(decision)
    # Conventionally, if the decision function is exactly zero, classify as +1.
    y_pred[y_pred == 0] = 1
    return y_pred

def cross_validate_svm(X, y, C_list, gamma_list, k=5):
    """
    Perform k-fold cross-validation to find the best hyperparameters (C, gamma).
    """
    from sklearn.model_selection import StratifiedKFold
    from sklearn.metrics import accuracy_score

    # Use StratifiedKFold to preserve class proportions in each fold.
    skf = StratifiedKFold(n_splits=k, shuffle=True, random_state=42)
    best_score = -np.inf # Initialize with a low value to ensure any valid score improves it.
    best_params = None

    # Iterate through all combinations of C and gamma hyperparameters.
    for C in C_list:
        for gamma in gamma_list:
            fold_scores = []
            # Iterate through each fold for cross-validation.
            for train_idx, val_idx in skf.split(X, y):
                X_tr, X_val = X[train_idx], X[val_idx]
                y_tr, y_val = y[train_idx], y[val_idx]

                # Train the SVM on the training fold.
                alpha, b, _ = solve_svm_dual_cvxopt(X_tr, y_tr, C, gamma)
                # Predict on the validation fold.
                preds = svm_predict(X_tr, y_tr, alpha, b, X_val, gamma)

                # Evaluate accuracy and store the score.
                score = accuracy_score(y_val, preds)
                fold_scores.append(score)

            # Calculate the average score across all folds for the current hyperparameters.
            avg_score = np.mean(fold_scores)
            # Optional: Print current parameters and average accuracy for monitoring.
            # print(f"C={C}, gamma={gamma}, Acc={avg_score:.4f}")

            # Update best parameters if the current average score is higher.
            if avg_score > best_score:
                best_score = avg_score
                best_params = (C, gamma)

    return best_params, best_score

def mvp_svm(X, y, C, gamma, max_iter=100000, tol=1e-3):
    """
    Most Violating Pair (MVP) Sequential Minimal Optimization (SMO) implementation.
    This algorithm iteratively updates two alpha values at a time to optimize the dual objective.
    """
    n_samples = X.shape[0]
    y = y.astype(float) # Ensure labels are float for calculations.

    # Precompute the kernel matrix (K). This can be memory-intensive for large datasets,
    # but significantly speeds up computation by avoiding redundant kernel evaluations.
    K = rbf_kernel(X, X, gamma)

    # Initialize alpha values to zero. These are the dual coefficients.
    alpha = np.zeros(n_samples)

    # f_no_b represents the decision function without the bias term: sum(alpha_k * y_k * K(x_k, x)).
    # Initially, with all alphas at zero, f_no_b is also zero.
    f_no_b = np.zeros(n_samples)

    it = 0 # Iteration counter.

    while it < max_iter:
        # The SMO algorithm works by finding the most violating pair of KKT conditions.
        # This often involves examining the residual, s = y - f_no_b.
        s = y - f_no_b

        # Identify indices where alpha can be increased (I_up) or decreased (I_low).
        # I_up: samples that violate the KKT condition for alpha_i < C (y_i*f(x_i) < 1).
        # (y_i = +1 and alpha_i < C) OR (y_i = -1 and alpha_i > 0).
        mask_up = ((y == 1) & (alpha < C - 1e-6)) | ((y == -1) & (alpha > 1e-6))

        # I_low: samples that violate the KKT condition for alpha_j > 0 (y_j*f(x_j) > 1).
        # (y_j = +1 and alpha_j > 0) OR (y_j = -1 and alpha_j < C).
        mask_low = ((y == 1) & (alpha > 1e-6)) | ((y == -1) & (alpha < C - 1e-6))

        I_up = np.where(mask_up)[0]
        I_low = np.where(mask_low)[0]

        # If no valid pairs can be found for optimization, convergence is reached.
        if len(I_up) == 0 or len(I_low) == 0:
            break

        # Select the 'i' index that maximizes s[i] among I_up.
        i = I_up[np.argmax(s[I_up])]
        # Select the 'j' index that minimizes s[j] among I_low.
        j = I_low[np.argmin(s[I_low])]

        # Stopping condition based on the maximal KKT violation (approximate duality gap).
        # If the violation is below tolerance, the algorithm has converged.
        if s[i] - s[j] < tol:
            break

        it += 1

        # --- Solve the subproblem for the pair (i, j) ---

        # Calculate the second derivative (curvature) of the objective function for the pair.
        # This is needed for the optimal step size.
        eta = K[i, i] + K[j, j] - 2 * K[i, j]

        # Handle cases where eta is non-positive (e.g., due to linear dependency or numerical issues).
        # A small positive value prevents division by zero.
        if eta <= 0:
            eta = 1e-12

        # Store old alpha values and labels for updates.
        ai_old, aj_old = alpha[i], alpha[j]
        yi, yj = y[i], y[j]

        # Calculate the clipping boundaries (L and H) for alpha_j.
        # These ensure that 0 <= alpha_i, alpha_j <= C and the equality constraint is maintained.
        if yi != yj:
            L = max(0.0, aj_old - ai_old)
            H = min(C, C + aj_old - ai_old)
        else:
            L = max(0.0, ai_old + aj_old - C)
            H = min(C, ai_old + aj_old)

        # If L >= H, no valid step can be made, so skip this pair.
        if L >= H:
            continue

        # Calculate the decision function values for points i and j.
        Ei = f_no_b[i] - yi
        Ej = f_no_b[j] - yj

        # Compute the unconstrained optimal step for alpha_j.
        aj_new = aj_old + yj * (Ei - Ej) / eta

        # Clip aj_new to adhere to the [L, H] bounds.
        if aj_new > H:
            aj_new = H
        elif aj_new < L:
            aj_new = L

        # If the change in alpha_j is too small, skip this iteration as no significant update occurred.
        if abs(aj_new - aj_old) < 1e-8:
            continue

        # Update alpha_i based on the linear equality constraint:
        # alpha_i * y_i + alpha_j * y_j = constant.
        s_sign = yi * yj
        ai_new = ai_old + s_sign * (aj_old - aj_new)

        # Update the alpha vector with the new values.
        alpha[i] = ai_new
        alpha[j] = aj_new

        # --- Vectorized update of f_no_b ---
        # Efficiently update f_no_b for all samples based on the changes in alpha_i and alpha_j.
        # f_new(x) = f_old(x) + (ai_new - ai_old)*yi*K(xi, x) + (aj_new - aj_old)*yj*K(xj, x).
        delta_ai = ai_new - ai_old
        delta_aj = aj_new - aj_old

        # This vectorized update is crucial for performance.
        f_no_b += (delta_ai * yi) * K[:, i] + (delta_aj * yj) * K[:, j]

    # --- Calculate the Bias 'b' ---
    # The bias 'b' is calculated using support vectors that lie exactly on the margin (0 < alpha < C).
    # For these points, y_k * f(x_k) = 1, so b = y_k - f_no_b[k].
    mask_sv_free = (alpha > 1e-6) & (alpha < C - 1e-6)
    if np.any(mask_sv_free):
        b = np.mean(y[mask_sv_free] - f_no_b[mask_sv_free])
    else:
        # If no free support vectors are found, average 'b' over all active support vectors (alpha > 0).
        # This is a less ideal but necessary fallback.
        mask_sv = (alpha > 1e-6)
        if np.any(mask_sv):
            b = np.mean(y[mask_sv] - f_no_b[mask_sv])
        else:
            # If no support vectors are found, set bias to zero.
            b = 0.0

    return alpha, b, it